### ISSUE TITLE
Makefile fails with dash as /bin/sh

### ISSUE THREAD

**Issue by kevincox** [joukewitteveen/xlogin#3]
There is some bash parameter expansion in the makefile that fails if `/bin/sh` isn't bash.  Since bash is required it should be declared in the makefile.  Setting the following variable should do the trick.

```make
SHELL := /bin/bash
```

**Comment by joukewitteveen** [comment]
This is fixed in ed76919ae72bcd87efb8206625a197da2c428063.

This commit introduces the following variables and their defaults in the Makefile.
```
BASH = /usr/bin/bash
SHELL := $(BASH)
```
Thus you can set the location of Bash that the installed files will refer to (in `BASH`) and the location of Bash to be used by `make` (in `SHELL`) in case it differs.
